language: node_js
node_js:
- '0.10'
install:
- npm install -g bower
- yes no | bower install --allow-root
- npm install -g requirejs
- npm install -g grunt-cli
- npm install
- gem install sass
before_script:
- grunt test
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
after_success:
- bash ops/after_success.sh
deploy:
  provider: releases
  api_key:
    secure: JQ26GqeJKXw1WSnDzQA8MelU/UZFAc7XECiVNXZbevfEOzSx4LAdn1wz5QR3fN83EcUkpsQuxPmmvX+7y12SmG2QEJsWgqvf6Bbo7qHXGpvYSYhrjN37Gr2Y32RdPKje7kkO4vHwxwoleHz+WbwAHsiax4gk+D7Haw27IeVlP5c=
  file: dist/auja.min.js
  on:
    repo: Label305/Auja
    tags: true
    all_branches: true
env:
  global:
  - secure: UD+S3gEXLgqTjtiKgze6AkSb6yRl6v7rx+hfHIvyRiR8od22sziHbxkt0dCdN26pYtIuD58H3AnDyJGZlbSUGhERpG3nPo6vcljM2TC1puky4bYlEqChxohPgMZWT6ue6QEYEC/4lCKwQikMXk7t4GmuoLSRyNPdEnHxulO2fwQ=
  - secure: afu9XELkbeWH7sbr2r5bY1ViZ+K+udCPHdfy8aJpWjiZWy1WKcntp+UUcCJY7efnMEh0nJSz8Z0X8BVERgaLnnQYKqUn3jcRvpArnkW4i+ikhjz1P4w6w+oOw1q0UVIzMlyzrHXE4D8yoxYGig+7Py6zuLhxHHXNGo2GW3oN31E=
notifications:
  slack:
    secure: WfIDH7lh11mOilLyu9re+mWV48RBrWN4BkKMjFM0mUZEB3xJQ1DnyeSa8AB/xEbAjwQqEgrwRwEePK4cijLFTSP+MAGkRYKnFsGmjo8i77ccNPtt9fDZUHMvjVPqKaNCpbOT8M7o3ovi9d8LAdQd4GdiQISY4vmBnEWiDn16thQ=
