language: node_js
node_js:
    - "0.10"
install:
    - npm install -g bower
    - yes no | bower install --allow-root
    - npm install -g requirejs
    - npm install -g grunt-cli
    - npm install
before_script:
    - grunt react
    - r.js -o build.js out=dist/auja.min.js
    - r.js -o build.js out=dist/auja.js optimize=none
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - npm test
